# Generated by Django 4.1.2 on 2022-10-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='destino',
            new_name='name',
        ),
    ]
