# Generated by Django 4.1.2 on 2022-10-28 22:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_destino_viaje_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
