# Generated by Django 4.1.2 on 2022-10-29 17:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
