# Generated by Django 4.1.2 on 2022-10-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_accommodation_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='price',
        ),
    ]
