# Generated by Django 4.1.2 on 2022-10-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0003_remove_accommodation_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='updated_at',
        ),
    ]
